2021-10-06 06:14:47 UTC Syncing #13363765 0x8b02…19de     0.10 blk/s   29.6 tx/s    2.4 Mgas/s      0+   24 Qed Ancient:#12416446 LI:#13363788   21/25 peers      4 MiB chain    8 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-06 06:14:47 UTC Syncing #13363765 0x8b02…19de     0.20 blk/s   59.2 tx/s    4.8 Mgas/s      0+   24 Qed Ancient:#12416446 LI:#13363788   21/25 peers      4 MiB chain    8 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-06 06:14:56 UTC Syncing #13363766 0x9779…500c     0.20 blk/s   27.6 tx/s    2.2 Mgas/s      0+   27 Qed Ancient:#12416447 LI:#13363792   16/25 peers      4 MiB chain    8 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-06 06:15:04 UTC Syncing #13363767 0xe592…fa9f     0.10 blk/s    7.0 tx/s    0.5 Mgas/s      0+   27 Qed Ancient:#12416448 LI:#13363793   16/25 peers      4 MiB chain    8 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-06 06:15:04 UTC Syncing #13363767 0xe592…fa9f     0.20 blk/s   14.0 tx/s    1.0 Mgas/s      0+   27 Qed Ancient:#12416448 LI:#13363793   16/25 peers      4 MiB chain    8 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-06 06:15:07 UTC Syncing #13363767 0xe592…fa9f     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   27 Qed Ancient:#12416448 LI:#13363793   12/25 peers      4 MiB chain    8 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-06 06:15:17 UTC Syncing #13363768 0x2ef5…2e26     0.20 blk/s   42.6 tx/s    3.6 Mgas/s      0+   26 Qed Ancient:#12416449 LI:#13363793   12/25 peers      4 MiB chain    8 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-06 06:15:17 UTC Syncing #13363769 0x4557…e8bc     0.20 blk/s   31.4 tx/s    2.6 Mgas/s      0+   25 Qed Ancient:#12416450 LI:#13363793   12/25 peers      4 MiB chain    8 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-06 06:15:26 UTC Syncing #13363769 0x4557…e8bc     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   27 Qed Ancient:#12416450 LI:#13363795   10/25 peers      4 MiB chain    8 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-06 06:15:27 UTC Syncing #13363769 0x4557…e8bc     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+   28 Qed Ancient:#12416450 LI:#13363796   10/25 peers      4 MiB chain    8 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2021-10-06 06:15:31 UTC Panic occured, see stderr for details


====================

   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   7: <journaldb::overlayrecentdb::OverlayRecentDB as hash_db::HashDB<keccak_hasher::KeccakHasher,elastic_array::ElasticArray128<u8>>>::get
   8: trie_db::triedbmut::TrieDBMut<H,C>::cache
   9: trie_db::triedbmut::TrieDBMut<H,C>::insert_at
  10: trie_db::triedbmut::TrieDBMut<H,C>::insert_inspector
  11: trie_db::triedbmut::TrieDBMut<H,C>::insert_at
  12: trie_db::triedbmut::TrieDBMut<H,C>::insert_inspector
  13: trie_db::triedbmut::TrieDBMut<H,C>::insert_at
  14: trie_db::triedbmut::TrieDBMut<H,C>::insert_inspector
  15: trie_db::triedbmut::TrieDBMut<H,C>::insert_at
  16: trie_db::triedbmut::TrieDBMut<H,C>::insert_inspector
  17: trie_db::triedbmut::TrieDBMut<H,C>::insert_at
  18: trie_db::triedbmut::TrieDBMut<H,C>::insert_inspector
  19: trie_db::triedbmut::TrieDBMut<H,C>::insert_at
  20: trie_db::triedbmut::TrieDBMut<H,C>::insert_inspector
  21: trie_db::triedbmut::TrieDBMut<H,C>::insert_at
  22: <trie_db::triedbmut::TrieDBMut<H,C> as trie_db::TrieMut<H,C>>::insert
  23: <trie_db::sectriedbmut::SecTrieDBMut<H,C> as trie_db::TrieMut<H,C>>::insert
  24: ethcore::state::State<B>::commit
  25: ethcore::block::OpenBlock::close_and_lock
  26: ethcore::client::client::Importer::import_verified_blocks
  27: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
  28: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  29: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  30: std::sys_common::backtrace::__rust_begin_short_backtrace
  31: core::ops::function::FnOnce::call_once{{vtable.shim}}
  32: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  33: start_thread
  34: __clone


Thread 'Worker Client0' panicked at 'Low-level database error. Some issue with your hard disk?: Custom { kind: Other, error: "IO error: While open a file for random read: /data/blockchain/eth-data/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/1483490.sst: No such file or directory" }', crates/db/journaldb/src/overlayrecentdb.rs:180

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-10-06 06:15:31 UTC Finishing work, please wait...
2021-10-06 06:15:31 UTC Panic occured, see stderr for details


====================

   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   7: <KVDB as ethcore_db::db::Readable>::read
   8: ethcore_blockchain::blockchain::BlockChain::epoch_transition
   9: ethcore::client::ancient_import::AncientVerifier::verify
  10: std::sys_common::backtrace::__rust_begin_short_backtrace
  11: core::ops::function::FnOnce::call_once{{vtable.shim}}
  12: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  13: start_thread
  14: __clone


Thread 'ancient_block_exec' panicked at 'db get failed, key: [5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 98, 100, 55, 53, 99, 51]: Custom { kind: Other, error: "IO error: While open a file for random read: /data/blockchain/eth-data/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/1291779.sst: No such file or directory" }', /data/blockchain/openethereum/crates/db/db/src/db.rs:294

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-10-06 06:15:31 UTC Panic occured, see stderr for details


====================

   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   7: ethcore::client::client::Client::shutdown
   8: openethereum::main
   9: std::sys_common::backtrace::__rust_begin_short_backtrace
  10: main
  11: __libc_start_main
  12: _start


Thread 'main' panicked at 'Join handle should not panic: Any', /home/longz/.cargo/git/checkouts/reth-1e6c266c722f7d6d/573e128/crates/util/src/queue/execution_queue.rs:59

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new


2021-10-06 06:15:31 UTC Panic occured, see stderr for details


====================

   0: panic_hook::set_with::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   6: core::option::expect_none_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
   7: <journaldb::overlayrecentdb::OverlayRecentDB as hash_db::HashDB<keccak_hasher::KeccakHasher,elastic_array::ElasticArray128<u8>>>::get
   8: <&mut dyn hash_db::HashDB<H,T> as hash_db::HashDBRef<H,T>>::get
   9: trie_db::lookup::Lookup<H,C,Q>::look_up
  10: ethcore::state::State<B>::nonce
  11: ethcore::client::traits::Nonce::latest_nonce
  12: <ethcore::miner::pool_client::CachedNonceClient<C> as ethcore_miner::pool::client::NonceClient>::account_nonce
  13: ethcore_miner::pool::queue::TransactionQueue::import::{{closure}}
  14: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  15: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  16: ethcore_miner::pool::queue::TransactionQueue::import
  17: ethcore::client::client::IoChannelQueue::queue::{{closure}}
  18: <ethcore_service::service::ClientIoHandler as ethcore_io::IoHandler<ethcore::client::io_message::ClientIoMessage>>::message
  19: ethcore_io::worker::Worker::new::{{closure}}::{{closure}}
  20: <futures::future::loop_fn::LoopFn<A,F> as futures::future::Future>::poll
  21: std::sys_common::backtrace::__rust_begin_short_backtrace
  22: core::ops::function::FnOnce::call_once{{vtable.shim}}
  23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/alloc/src/boxed.rs:1521:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys/unix/thread.rs:71:17
  24: start_thread
  25: __clone


Thread 'Worker Client3' panicked at 'Low-level database error. Some issue with your hard disk?: Custom { kind: Other, error: "IO error: While open a file for random read: /data/blockchain/eth-data/chains/ethereum/db/906a34e69aec8c0d/overlayrecent/db/1557599.sst: No such file or directory" }', crates/db/journaldb/src/overlayrecentdb.rs:180

This is a bug. Please report it at:

    https://github.com/openethereum/openethereum/issues/new